### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by balassy** [mavezeau/TeamCitySharp#12]
As a .NET developer, I would like to have this library to target .NET Standard or .NET Core, so I can use it from my .NET Core application. Do you have any plans to change the target framework?

Thank you for creating and maintaining this package!

**Comment by mavezeau** [comment]
I already try to convert but I need to made a big refactoring for this for the moment because one dependencies didn't support .net core..

**Comment by mavezeau** [comment]
but It's already include on my todo list... :)

**Comment by mavezeau** [comment]
First official release today => Done
