### ISSUE TITLE
Unable to get percentage complete of a running build

### ISSUE THREAD

**Issue by balassy** [mavezeau/TeamCitySharp#15]
Hello Marc-Andre,

I am unable to figure out how to get the `Running_info` property of the `Build` populated, because I cannot find a `BuildField` member related to this field..  Can you please help me out with a sample? 

I see from the source that it is mapped to the `running-info` property in the server response, which seems to be okay. However the `CamelCaseJsonFormatter` does not look to be able to handle the `_` character in the property name. As I see this is the only property with an underscore in the name, all others are PascalCase. Maybe it's a bug?

Thank you.

**Comment by mavezeau** [comment]
Please retry with the latest version 2.0.4
