### ISSUE TITLE
How to use TeamCitySharp NuGet Package on .Net Core

### ISSUE THREAD

**Issue by Rajkumar-Uppala** [mavezeau/TeamCitySharp#19]
HI Team,
Currently we are using "TeamCitySharp-forked-mavezeau" NuGet Package whose version is "1.0.62" for .Net 4.5.2 Framework application which is working as expected.

Now we have a requirement to implement the same for **.Net Core** application.

Could you please suggest me whether we have anything which supports .Net Core applications or any workarounds to meet this requirement.

Please advise.

Thanks,
Rajkumar Uppala.

**Comment by owena1337** [comment]
This project now compiles for .NET Standard. Just compile and reference the .dll in your solution, or create a NuGet package to target .NET Standard.

**Comment by mavezeau** [comment]
Now, the first version official with dotnet core is available

**Comment by Rajkumar-Uppala** [comment]
Thanks @mavezeau for sharing the information.
Could you please confirm is the version 2.0.0 under https://www.nuget.org/packages/TeamCitySharp-forked-mavezeau? holds this feature

Thanks,
Rajkumar Uppala.
