### ISSUE TITLE
Nuget Version is 2.0.4 but version in master is 2.0.0-beta1

### ISSUE THREAD

**Issue by SonnyCampbell** [mavezeau/TeamCitySharp#22]
Hey,

I'm honestly delighted to find a project like this! I thought I was going to have to write up everything myself from scratch, but there's a huge amount of stuff here already that will be so valuable. 

I wanted to update the repo with a few pieces of functionality that I need and I figure would be useful for other people too, however the nuget Version is 2.0.4 but the csproj master version is 2.0.0-beta1.

Am I missing something here, or where can I grab the latest version of code?

**Comment by mavezeau** [comment]
Yes it's my fault... 

The nuget version was not linked to the csproj but all code here are up to date. I will fix tthis soon
