### ISSUE TITLE
Count in Builds.ByBuildConfig

### ISSUE THREAD

**Issue by Dustymcp** [mavezeau/TeamCitySharp#7]
Hi guys
Thanks for the awesome library, saved me a ton of grief, im retrieving data from the server currently and running into issues regarding the max count while using the BuildsFields.

`var buildField = BuildField.WithFields(id: true, number: true, status: true, startDate: true, finishDate: true, buildTypeId: true, buildType: new TeamCitySharp.Fields.BuildTypeField());
            var buildsFields = BuildsField.WithFields(buildField: buildField, count: true);
            var currentListBuild = Client.Builds.GetFields(buildsFields.ToString()).ByBuildConfigId(buildConfigId);`

How can i manipulate the count to access maximum builds, the param is there i just cant figure out how to change the default from 100.

**Comment by mavezeau** [comment]
Hi Dustymcp,

By default, it's a issue with Teamcity directly, but I have a workaround for you. Just add a new parameter on your method to specify your max value.

Ex: (Max 10 builds)
`var currentListBuild = m_client.Builds.GetFields(buildsFields.ToString()).ByBuildConfigId(buildConfigId,new List<string> {"count(10)"});`

Regards,
Marc-Andre Vezeau
