### ISSUE TITLE
Unable to get tags by locator

### ISSUE THREAD

**Issue by K1llMan** [mavezeau/TeamCitySharp#9]
Hi!
Code

`tcClient.Builds.ByBuildLocator(BuildLocator.WithNumber(artNum)).FirstOrDefault()`

returns build object without tags but

`tcClient.Builds.ById(build.Id)`

returns correctly parsed tags structure. 
Is it REST API problem or issue?
How tags can be added to build?

**Comment by mavezeau** [comment]
It's a normal side effect deom teamcity. 
EX: if you see this query on your server
http://teamcity/httpAuth/app/rest/builds
you don't have the same data if you use a build id 
http://teamcity/httpAuth/app/rest/builds/id:8126625

But we have a workaround ... The fields ... 
```var ttt = 8022386;
 // Create Field data (cherry pick field...) 
 TagField tagField = TagField.WithFields(name:true);
 TagsField  tagsField = TagsField.WithFields(tagField);
 BuildField buildField = BuildField.WithFields(id:true, tags:tagsField);
 BuildsField buildsField= BuildsField.WithFields(buildField: buildField);

 // Call to API
 var oo = m_client.Builds.GetFields(buildsField.ToString()).ByBuildLocator(BuildLocator.WithId(ttt)).FirstOrDefault();
```
